[metadata]
name = TempEst-NEXT
version = 0.1.5
author = Daniel Philippus
author_email = daniel@dphilippus.com
description = TempEst-NEXT, Stream Temperature Estimation - Near-term Expected Temperatures: a statistical stream temperature model with coefficient estimation for ungaged watersheds
long_description = file: README.md
long_description_content_type = text/markdown
url = https://rivertempest.org/next/readme.html
project_urls = 
	Bug Tracker = https://github.com/mines-ciroh/tempest-next/issues
	Source Code = https://github.com/mines-ciroh/tempest-next
classifiers = 
	Programming Language :: Python :: 3
	License :: OSI Approved :: GNU General Public License v3 (GPLv3)

[options]
package_dir = 
	= src
packages = find:
python_requires = >=3.0
install_requires = 
	pandas
	numpy>=2
	TempEst-NEWT
	pygam>=0.10
	pydaymet>=0.19
	pygridmet
	pynldas2
	dataretrieval
	geopandas
	pynhd>=0.19
	pygeohydro
	py3dep
	xarray-spatial
	rioxarray
	s3fs
	zarr
	cartopy
	metpy
	getgfs
	dask
	cfgrib
	
	

[options.packages.find]
where = src

[options.package_data]
* = *.pickle

[egg_info]
tag_build = 
tag_date = 0
