# -*- coding: utf-8 -*-
"""
Created on Thu Nov  7 13:13:41 2024

@author: dphilippus

This file covers data preparation for the reach model.  It is initially
written for design of the reach model, not production implementation, but
may prove useful for the latter.

At first pass, this simply reimplements the components designed for preliminary
reach analysis in fully-automated form.
"""

from NEXT import NEXT
import NEXT.data as data
import dataretrieval.nwis as nwis
import pandas as pd
import numpy as np
import os
import matplotlib.pyplot as plt

def get_all_data(raw_id, dist, buffer, start, end, cache_base=None,
                 plot_ws=False):
    """
    Retrieve all required data for the specified location and tributaries,
    caching if desired.

    Parameters
    ----------
    raw_id : str
        USGS gage id.
    dist : float
        Main reach length in km.  Above that distance will be a lumped model.
    buffer : float
        Reach buffer width in m for data retrieval.  At least 100 m is recommended
        to avoid no-data errors.
    start : str
        Start date in yyyy-mm-dd.
    end : str
        End date in yyyy-mm-dd.
    cache_base : str, optional
        Directory in which to cache results (recommended).  If specified, results
        will be stored in cache_base/inputs_<raw_id>_<dist>km_<buffer>m.csv.
        Data retrieval is quite slow, so caching results is recommended.
    plot_ws : bool, optional
        If true and there is not a cached input, plot the retrieved watershed geometry.

    Returns
    -------
    A data frame covering the mainstem, upstream watershed, and tributary
    watersheds with columns id, id_type (e.g., tributary, mainstem) plus all
    TempEst-NEXT inputs.

    """
    site = f"usgs:{raw_id}"
    if cache_base is not None:
        path = cache_base + f"inputs_{raw_id}_{dist}km_{buffer}m.csv"
        if os.path.exists(path):
            return pd.read_csv(path, dtype={"id": "str"}, parse_dates=True)
    (trib, up, main) = data.get_upstream(site, dist)
    if plot_ws:
        ax = up.plot(color="green")
        trib.plot(ax=ax, color="blue")
        main.plot(ax=ax, color="red")
        plt.show()
    inputs = data.all_data_reaches(site, dist, buffer,
                                   start, end, as_df=True)
    if cache_base is not None:
        inputs.to_csv(path, index=False)
    return inputs


def compute_noreach(inputs, nxmod):
    """
    Compute 'no-reach' (area-weighted mean of contributing watersheds) temperature.
    It is assumed that the reach is <1 day long, so timing is ignored.

    Parameters
    ----------
    inputs : pandas.DataFrame
        Input dataframe as generated by get_all_data.
    nxmod : NEXT.NEXT
        NEXT model to use for lumped watersheds.

    Returns
    -------
    Data frame of date, tmod, where tmod is no-reach modeled temperature.

    """
    subws = inputs[inputs["id_type"] != "mainstem"]
    inp_preds = subws.groupby("id").apply(
        lambda x: nxmod.run(x, reset=True, use_climate=False),
        include_groups=False).reset_index()
    tot_area = inp_preds.groupby("id")["area"].agg("first").sum()
    noreach = inp_preds.assign(
        tmod = lambda x: x["temp.mod"] * x["area"] / tot_area).groupby(
            "date", as_index=False)["tmod"].agg("sum")
    return noreach

def noreach_withobs(inputs, nxmod, raw_id, start, end):
    """
    Compute 'no-reach' temperature and add observed temperature and discharge
    columns.

    Parameters
    ----------
    inputs : pandas.DataFrame
        Input dataframe as generated by get_all_data.
    nxmod : NEXT.NEXT
        NEXT model to use for lumped watersheds.
    raw_id : str
        USGS gage id.
    start : str
        Start date in yyyy-mm-dd.
    end : str
        End date in yyyy-mm-dd.

    Returns
    -------
    Inputs data frame, with added columns tmod (no-reach temp), Q (observed flow),
    temperature (observed), and delta (observed minus tmod).

    """
    tobs = nwis.get_dv(
        sites=[raw_id], start="2015-01-01", end="2022-12-31",
        parameterCd="00010")[0].assign(
            date=lambda x: pd.to_datetime(x.index.date)
            )[["date", "00010_Mean"]].rename(
                columns={"00010_Mean": "temperature"}).dropna()
    qobs = nwis.get_dv(sites=[raw_id], start="2015-01-01", end="2022-12-31",
                       parameterCd="00060")[0].assign(
                           date=lambda x: pd.to_datetime(x.index.date)
                           )[["date", "00060_Mean"]].rename(
                               columns={"00060_Mean": "Q"}).dropna()
    noreach = compute_noreach(inputs, nxmod)
    comb = noreach.merge(tobs, on="date").merge(qobs, on="date").\
        assign(delta = lambda x: x["temperature"] - x["tmod"])
    rivdat = inputs[inputs["id_type"] == "mainstem"]
    return comb.merge(rivdat, on="date")

def monoreach_maker(alpha, r, k, q):
    """
    Prepare a monoreach (uniform equilibration) prediction function using
    a simple equilibrium solution:
        DeltaT = (Tair-T) * (1-exp(-alpha/Q^q)) + (beta*srad + k)/Q^q
    
    This implementation assumes that stream temperature equilibration occurs
    through linear heat exchange with the air (thus, exponential decay of the
    difference), a constant solar radiation temperature input, and a constant
    "other flux" term (e.g., groundwater input), all of which has sensitivity
    inversely proportional to some power of discharge (which approximates depth).
    
    All four arguments are calibrated.
    
    The equation is not dimensionally consistent; each coefficient lumps several
    intermediate coefficients and would come out with bizarre and variable units
    (varying with q).  Therefore, the inputs must be in consistent units
    (Celsius, W/m2, and m3/s).

    Parameters
    ----------
    alpha : float
        Air sensitivity coefficient.
    r : float
        Radiation sensitivity coefficient.
    k : float
        Constant flux coefficient.
    q : float
        Flow sensitivity coefficient.

    Returns
    -------
    function: pandas.DataFrame --> np.array
        Function which, given an input dataframe with tmax (air temperature),
        tmod, Q, srad, returns an array of temperature change predictions.

    """
    def delta(indat):
        return (indat["tmax"] - indat["tmod"]) * (
            1 - np.exp(-alpha / (indat["Q"] ** q))) - (
                r * indat["srad"] + k) / (indat["Q"] ** q)
    return delta

def reachperf(alpha, r, k, q, indat):
    """
    Computes performance, as R (not R2, since high performance in the wrong
    direction is possible), for the given set of coefficients.

    Parameters
    ----------
    alpha : float
        Air sensitivity coefficient.
    r : float
        Radiation sensitivity coefficient.
    k : float
        Constant flux coefficient.
    q : float
        Flow sensitivity coefficient.
    indat : pandas.DataFrame
        Input data frame containing tmax, tmod, Q, srad, delta (observed).

    Returns
    -------
    float
        Correlation coefficient between modeled and observed Delta-T.

    """
    dmod = monoreach_maker(alpha, r, k, q)(indat)
    dobs = indat["delta"]
    return dmod.corr(dobs)


def mk_range(low, high, N=5):
    """
    Generate an array covering N increments across the specified values,
    inclusive.

    Parameters
    ----------
    low : float
        Low value.
    high : float
        High value.
    N : int, optional
        DESCRIPTION. The default is 5.

    Returns
    -------
    None.

    """


def search_reach_coefficients(indat, arange, rrange, krange, qrange,
                              tolerance=0.005, validate=True, log=False):
    """
    Searches the parameter space to identify optimal coefficients.  Returns
    optimal coefficients, and their performance as R.  If validate is true,
    return performance for a separate validation set.

    Parameters
    ----------
    indat : pandas.DataFrame
        Input data frame containing tmax, tmod, Q, srad, delta.
    arange : (float, float)
        Minimum and maximum permitted values for alpha.
    rrange : (float, float)
        Minimum and maximum permitted values for r.
    krange : (float, float)
        Minimum and maximum permitted values for k.
    qrange : (float, float)
        Minimum and maximum permitted values for q.
    tolerance : float, optional
        Performance threshold for convergence. The default is 0.005.
    validate: bool, optional
        Whether to report performance for a separate validation set.
    log: bool, optional
        Whether to also return a data frame of iterations.

    Returns
    -------
    ((float, float, float, float), float)
        Tuple of optimal alpha, r, k, q; then R

    """
    if validate:
        cut = round(len(indat) * 0.7)
        train = indat.iloc[:cut]
        test = indat.iloc[cut:]
    else:
        train = indat
        test = indat
    
    """
    The search algorithm.
    
    1. Test performance for all combinations of 5 evenly-spaced values in
        allowed ranges (625 tests).
    2. For each variable, compute the range covered in the best 25 runs.
        If they are all on one side of the midpoint and <half are at the associated
        extreme, change the range to that side.
        If >half are at one extreme, double the range on that side, and retract
        the other side halfway.
        If they are all in the middle, narrow the range to the middle.
        Otherwise, do not modify the range.
    3. Rerun the test. If the new best is <tolerance better than the old best,
        halt and return the new best.  Otherwise, continue.
    """
    best = -1
    delta = 1
    if log:
        history = {"alpha": [], "r": [], "k": [], "q": [], "R": []}
    while delta > tolerance:
        params = pd.DataFrame({"A": unrg(Amin, Amax)}).\
            merge(pd.DataFrame({"B": unrg(Bmin, Bmax)}), how="cross").\
            merge(pd.DataFrame({"C": unrg(Cmin, Cmax)}), how="cross").\
            merge(pd.DataFrame({"q": unrg(qmin, qmax)}), how="cross")
        params["R"] = params.apply(lambda x: reachperf(x["A"], x["B"], x["C"], x["q"]), axis=1)
    
